name: Trigger Monorepo Update

on:
  push:
    branches:
      - main

jobs:
  trigger_monorepo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Monorepo Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const repoOwner = 'inx-omnish';
            const monorepoName = 'version-control-turbo';
            await github.repos.createDispatchEvent({
              owner: repoOwner,
              repo: monorepoName,
              event_type: 'update_from_individual_repo',
              client_payload: { repo: process.env.GITHUB_REPOSITORY }
            });
