name: Trigger Monorepo Update

on:
  push:
    branches:
      - main

jobs:
  trigger_monorepo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Monorepo Workflow
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $PAT_TOKEN" \
          https://api.github.com/repos/inx-omnish/version-control-turbo/dispatches \
          -d '{"event_type": "update_from_individual_repo", "client_payload": { "repo": "${{ github.repository }}" }}'
