name: Sync Changes from Individual Repos

on:
  repository_dispatch:
    types: [update_from_individual_repo]

jobs:
  sync_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for the monorepo

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Identify Source Repo
        id: source_repo
        run: |
          echo "SOURCE_REPO=${{ github.event.client_payload.repo }}" >> $GITHUB_ENV

      - name: Fetch Changes from Source Repo
        run: |
          if [[ "$SOURCE_REPO" == *"/version-control-turbo-doc" ]]; then
            git remote add doc-repo https://github.com/inx-omnish/version-control-turbo-doc.git
            git fetch doc-repo main
            git checkout doc-repo/main -- .  # Checkout the content of the doc repo
          elif [[ "$SOURCE_REPO" == *"/version-control-turbo-web" ]]; then
            git remote add web-repo https://github.com/inx-omnish/version-control-turbo-web.git
            git fetch web-repo main
            git checkout web-repo/main -- .  # Checkout the content of the web repo
          fi

      - name: Overwrite Content in Target Directory
        run: |
          if [[ "$SOURCE_REPO" == *"/version-control-turbo-doc" ]]; then
            # Sync content from doc repo to apps/docs in the monorepo
            rsync -av --exclude='.git' --delete ./ apps/docs/
          elif [[ "$SOURCE_REPO" == *"/version-control-turbo-web" ]]; then
            # Sync content from web repo to apps/web in the monorepo
            rsync -av --exclude='.git' --delete ./ apps/web/
          fi


      - name: Create Branch and Push Changes
        run: |
          TIMESTAMP=$(date +%s)
          BRANCH_NAME="sync-${SOURCE_REPO##*/}-${TIMESTAMP}"
          git checkout -b $BRANCH_NAME
          git commit -m "Sync changes from $SOURCE_REPO to monorepo"
          git push https://x-access-token:${{ secrets.MONOREPO_PAT }}@github.com/inx-omnish/version-control-turbo.git $BRANCH_NAME
        env:
          SOURCE_REPO: inx-omnish/version-control-turbo-doc


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MONOREPO_PAT }}
          branch: $BRANCH_NAME
          title: "Sync updates from $SOURCE_REPO"
          body: "Automated PR to sync changes from $SOURCE_REPO to the appropriate subdirectory in monorepo."
          base: main
