name: Sync Changes from Individual Repos

on:
  repository_dispatch:
    types: [update_from_individual_repo]

jobs:
  sync_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MONOREPO_PAT }}  # Use a personal access token for repo access
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Identify Source Repo
        id: source_repo
        run: |
          echo "SOURCE_REPO=${{ github.event.client_payload.repo }}" >> $GITHUB_ENV

      - name: Fetch Changes from Source Repo
        run: |
          if [[ "$SOURCE_REPO" == *"/version-control-turbo-web" ]]; then
            git remote add web-repo https://github.com/inx-omnish/version-control-turbo-web.git
            git fetch web-repo main
          elif [[ "$SOURCE_REPO" == *"/version-control-turbo-doc" ]]; then
            git remote add doc-repo https://github.com/inx-omnish/version-control-turbo-doc.git
            git fetch doc-repo main
          fi

      - name: Merge Changes from Source Repo to Monorepo Subdirectory
        run: |
          if [[ "$SOURCE_REPO" == *"/version-control-turbo-web" ]]; then
            git checkout web-repo/main -- .
            mkdir -p apps/web
            cp -R ./* apps/web  # Copy the changes to apps/web directory
          elif [[ "$SOURCE_REPO" == *"/version-control-turbo-doc" ]]; then
            git checkout doc-repo/main -- .
            mkdir -p apps/doc
            cp -R ./* apps/doc  # Copy the changes to apps/doc directory
          fi

      - name: Commit Changes to New Branch
        run: |
          TIMESTAMP=$(date +%s)
          BRANCH_NAME="sync-${SOURCE_REPO##*/}-${TIMESTAMP}"
          git checkout -b $BRANCH_NAME
          git add apps/web apps/doc  # Stage the relevant subdirectory changes
          git commit -m "Sync updates from ${SOURCE_REPO##*/} to /apps directory"
          git push origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.MONOREPO_PAT }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MONOREPO_PAT }}
          branch: $BRANCH_NAME
          title: "Sync updates from $SOURCE_REPO"
          body: "Automated PR to sync changes from $SOURCE_REPO main branch to /apps."
          base: main
