name: Sync Changes from Individual Repos

on:
  repository_dispatch:
    types: [update_from_individual_repo]

jobs:
  sync_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for the monorepo

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Identify Source Repo
        id: source_repo
        run: |
          echo "SOURCE_REPO=${{ github.event.client_payload.repo }}" >> $GITHUB_ENV

      - name: Fetch Changes from Source Repo
        run: |
          if [[ "$SOURCE_REPO" == *"/version-control-turbo-doc" ]]; then
            git remote add doc-repo https://github.com/inx-omnish/version-control-turbo-doc.git
            git fetch doc-repo main
          elif [[ "$SOURCE_REPO" == *"/version-control-turbo-web" ]]; then
            git remote add web-repo https://github.com/inx-omnish/version-control-turbo-web.git
            git fetch web-repo main
          fi

      - name: Ensure Target Directory Exists
        run: |
          if [[ "$SOURCE_REPO" == *"/version-control-turbo-doc" ]]; then
            mkdir -p apps/docs  # Ensure apps/docs exists for doc repo
          elif [[ "$SOURCE_REPO" == *"/version-control-turbo-web" ]]; then
            mkdir -p apps/web  # Ensure apps/web exists for web repo
          fi

      - name: Merge Changes into Correct Subdirectory
        run: |
          if [[ "$SOURCE_REPO" == *"/version-control-turbo-doc" ]]; then
            git checkout doc-repo/main -- apps/docs  # Merge only changes to apps/docs
          elif [[ "$SOURCE_REPO" == *"/version-control-turbo-web" ]]; then
            git checkout web-repo/main -- apps/web  # Merge only changes to apps/web
          fi

      - name: Create Branch for Sync Changes
        run: |
          TIMESTAMP=$(date +%s)
          BRANCH_NAME="sync-${SOURCE_REPO##*/}-${TIMESTAMP}"
          git checkout -b $BRANCH_NAME
          git add apps/docs  # Add only the changes in apps/docs or apps/web
          git commit -m "Sync changes from $SOURCE_REPO to monorepo"
          git push origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.MONOREPO_PAT }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MONOREPO_PAT }}
          branch: $BRANCH_NAME
          title: "Sync updates from $SOURCE_REPO"
          body: "Automated PR to sync changes from $SOURCE_REPO to the appropriate subdirectory in monorepo."
          base: main
