name: Sync Changes from Individual Repos

on:
  repository_dispatch:
    types: [update_from_individual_repo]

jobs:
  sync_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for the monorepo

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Identify Source Repo
        id: source_repo
        run: |
          echo "SOURCE_REPO=${{ github.event.client_payload.repo }}" >> $GITHUB_ENV

      - name: Fetch Changes from Source Repo
        run: |
          if [[ "$SOURCE_REPO" == *"/version-control-turbo-doc" ]]; then
            git remote add doc-repo https://github.com/inx-omnish/version-control-turbo-doc.git
            git fetch doc-repo main
          elif [[ "$SOURCE_REPO" == *"/version-control-turbo-web" ]]; then
            git remote add web-repo https://github.com/inx-omnish/version-control-turbo-web.git
            git fetch web-repo main
          fi

      - name: Checkout Full Changes from Source Repo into Target Directory
        run: |
          if [[ "$SOURCE_REPO" == *"/version-control-turbo-doc" ]]; then
            # Checkout all changes from doc repo into /apps/docs directory in the monorepo
            git checkout doc-repo/main -- .
            git rm -r --cached apps/web  # Remove web-related files if any
            mv * apps/docs  # Move everything from the root to apps/docs
            git add apps/docs  # Add the changes to apps/docs
          elif [[ "$SOURCE_REPO" == *"/version-control-turbo-web" ]]; then
            # Checkout all changes from web repo into /apps/web directory in the monorepo
            git checkout web-repo/main -- .
            git rm -r --cached apps/docs  # Remove doc-related files if any
            mv * apps/web  # Move everything from the root to apps/web
            git add apps/web  # Add the changes to apps/web
          fi

      - name: Create Branch for Sync Changes
        run: |
          TIMESTAMP=$(date +%s)
          BRANCH_NAME="sync-${SOURCE_REPO##*/}-${TIMESTAMP}"
          git checkout -b $BRANCH_NAME
          git commit -m "Sync changes from $SOURCE_REPO to monorepo"
          git push origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.MONOREPO_PAT }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MONOREPO_PAT }}
          branch: $BRANCH_NAME
          title: "Sync updates from $SOURCE_REPO"
          body: "Automated PR to sync changes from $SOURCE_REPO to the appropriate subdirectory in monorepo."
          base: main
